name: Deploy

on:
  push:
    branches: [release/*]

jobs:
  main:
    runs-on: ubuntu-latest
    name: Main
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: corepack enable pnpm
      - run: pnpm install --frozen-lockfile
        name: Deploy
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          secrets: |
            DISCORD_APPLICATION_ID
            DISCORD_PUBLIC_KEY
            DISCORD_TOKEN
            YAHOO_APP_ID
        env:
          DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
          DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          YAHOO_APP_ID: ${{ secrets.YAHOO_APP_ID }}
